<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<button class="btn btn-primary">
  <a href="<?= $this->url('album', ['action' => 'add']) ?>" style="color: white; text-decoration:none">Add new album</a>
</button>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
  </tr>
  <?php foreach ($albums as $album) : ?>
    <tr>
      <td><?= $this->escapeHtml($album->title) ?></td>
      <td><?= $this->escapeHtml($album->artist) ?></td>
      <td>
        <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
        <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>